### ISSUE TITLE
从请求开始到响应结束，框架内部对于传输层TCP、应用层HTTP，完整的处理流程是怎样的？

### ISSUE THREAD

**Issue by pygyme** [AquiverV/aquiver#60]

**Comment by i1619kHz** [comment]
@pygyme 目前请先自行看代码吧，具体的类和方法可以看:
```org.aquiver.Aquiver.start()``` 主要用于调用NettyServer的start方法用于启动http服务器
```org.aquiver.server.NettyServer``` 基于netty实现的http服务器，在这里做初始化，类扫描，加载
```org.aquiver.server.NettyServerHandler``` 实现```SimpleChannelInboundHandler```会作为请求入口，http请求从这里可以获取到，由```NettyServerInitializer```注册```HttpServerCodec```进行解析后先传到```WebSocketHandler```，再传到```NettyServerHandler```处理，然后就是参数解析、处理、转换、注入、匹配路由、执行、返回结果后通过netty返回

其他的内容就比较简单了，挨个看就好。

**Comment by i1619kHz** [comment]
aquiver还支持依赖注入，配置文件注入之类的功能，用的我写的另外一个库apex，如果不太在意这方面的实现可以不看。
